// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Cart struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ProdID    uuid.UUID
	UpdatedAt time.Time
	Price     int32
	Quantity  int32
}

type Order struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ProdID    uuid.UUID
	CreatedAt time.Time
	Price     int32
	Quantity  int32
}

type Product struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description string
	Image       string
	Price       int32
	Quantity    int32
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Email     string
	Password  string
}
